---
new_page_extension: md
auto_deploy: true
admin_path: admin
webhook_url: 
sections:
- type: document
  path: content/_index.md
  label: Home
  templates:
  - home_page
- type: directory
  path: content/pages
  label: Pages
  create: all
  match: "*"
  templates:
  - page
- type: directory
  path: content/photos
  label: Photos
  create: all
  match: "*"
  templates:
  - photos
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
version: '0.48'
